/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import model.Usuario;

import dao.HistoricoDAO;
import javax.swing.*;
import java.util.List;
import model.Historico;

/**
 *
 * @author dante
 */
public class TelaHistorico extends javax.swing.JFrame {
    private Usuario usuario;
    private int usuarioId;
    private JTextArea txtBuscadas;
    private JTextArea txtCurtidas;
    private JTextArea txtDescurtidas;

    /**
     * Creates new form telaHistorico
     */
    public TelaHistorico(Usuario usuarioLogado) {
        this.usuario = usuarioLogado;
        

        initComponents();
        
        setSize(430, 430);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(null);
        
        this.txtBuscadas = jTextArea1;
        this.txtCurtidas = jTextArea2;
        this.txtDescurtidas = jTextArea3;
        
        carregarHistorico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Músicas buscadas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 100, 30);

        jLabel2.setText("Musicas curtidas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 30, 100, 30);

        jLabel3.setText("Músicas descurtidas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 30, 120, 30);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(302, 371, 92, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 90, 290);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(150, 70, 90, 290);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(270, 70, 90, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    new TelaPrincipal(usuario).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    
     private void carregarHistorico() {
    try {
        HistoricoDAO dao = new HistoricoDAO();

        List<String> buscadas = dao.buscarUltimasBuscadas(usuario.getId());
        List<String> curtidas = dao.buscarCurtidas(usuario.getId());
        List<String> descurtidas = dao.buscarDescurtidas(usuario.getId());

        System.out.println("Buscadas: " + buscadas);
        System.out.println("Curtidas: " + curtidas);
        System.out.println("Descurtidas: " + descurtidas);

        txtBuscadas.setText(String.join("\n", buscadas));
        txtCurtidas.setText(String.join("\n", curtidas));
        txtDescurtidas.setText(String.join("\n", descurtidas));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar histórico: " + e.getMessage());
    }
}
     
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
